sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:slug_title/
        path: blog/_posts
        taxonomies:
         - tags
         - categories
         - authors

    sysadmin:
      path: sysadmins-guide
      type: path

    developer:
      path: developers-guide
      type: path

    designer:
      path: designers-guide
      type: path


sculpin:
    ignore:
        - assets/css/_imports/

sculpin_less:
    files:
        - assets/css/basic.less

sculpin_algolia:
  application_id: 'DX6UMWHNHY'
  index_name:     'developers.shopware.com_prod'
